### ISSUE TITLE
Failed to compile on ubuntu 16.04.3 against lede master branch.

### ISSUE THREAD

**Issue by leonmorlando22** [zhangjingye03/qca-nss-gmac#2]
It could be that it just doesn't work on LEDE and requires OpenWRT trunk exclusively, but I'd just like to confirm. I'm attempting to compile this repo against LEDE master branch for a Nighthawk X4 (R7500 v2) target which comes with kernel 4.9. Compiling just the driver repo works, but when compiling both the driver and this one together I'm getting the [following errors](https://pastebin.com/vNXrVRuh).  
Am I doing something wrong? Missing a package or attempting to compile against a wrong branch?

**Comment by zhangjingye03** [comment]
Sorry, this repo was last updated 2 years ago which I've nearly forgotten what I had done at that time...
I checked my backup files, which show that at that time, the kernel version was still at 3.18.29. Lots of kernel headers may have changed in such a huge version difference. You can check [here](https://us.codeaurora.org/cgit/quic/qsdk/oss/lklm/nss-gmac) where I got the code for some updates.

**Comment by zhangjingye03** [comment]
I had a glance at the codeaurora, maybe [this](https://source.codeaurora.org/quic/qsdk/oss/lklm/nss-gmac/commit/?h=NHSS.QSDK.8.0.r2&id=0311bed57aab8a49ffeddbac9e4d6fe2394a3118) commit can help you

**Comment by mometto** [comment]
That commit helped! With that and some other minor changes I managed to compile the 3 modules against OpenWRT/LEDE trunk. However on boot there are some errors...

[   80.700292] qca_nss_drv: Unknown symbol nss_gmac_receive (err 0)
[   80.702192] qca_nss_drv: Unknown symbol nss_gmac_is_in_open_state (err 0)
[   80.708269] qca_nss_drv: Unknown symbol nss_gmac_start_data_plane (err 0)
[   80.714872] qca_nss_drv: Unknown symbol nss_gmac_override_data_plane (err 0)
[   80.721707] qca_nss_drv: Unknown symbol nss_gmac_get_netdev_by_macid (err 0)
[   80.728854] qca_nss_drv: Unknown symbol nss_gmac_restore_data_plane (err 0)
[   80.735807] qca_nss_drv: Unknown symbol nss_gmac_event_receive (err 0)
[   80.770730] qca_nss_drv: Unknown symbol nss_gmac_receive (err 0)
[   80.770806] qca_nss_drv: Unknown symbol nss_gmac_is_in_open_state (err 0)
[   80.775875] qca_nss_drv: Unknown symbol nss_gmac_start_data_plane (err 0)
[   80.782666] qca_nss_drv: Unknown symbol nss_gmac_override_data_plane (err 0)
[   80.789415] qca_nss_drv: Unknown symbol nss_gmac_get_netdev_by_macid (err 0)
[   80.796477] qca_nss_drv: Unknown symbol nss_gmac_restore_data_plane (err 0)
[   80.803567] qca_nss_drv: Unknown symbol nss_gmac_event_receive (err 0)
[   80.850167] **********************************************************

Do you know the latest OpenWRT commit on which the module were working unmodified?

**Comment by leonmorlando22** [comment]
https://github.com/quarkysg/openwrt/tree/lede-17.01-qca-nss
The person maintaining this repo has patches to compile the entire NSS stack (crypto, drv, gmac and qrfs). This repo is geared towards the R7800 though so you'll have to assess the entire code to adapt it for your device. I had no luck because flashing the resulting image bootloops my router no matter how I change the code, so good luck.

**Comment by mometto** [comment]
Thanks . 
@zhangjingye03 , do you know on which OpenWRT commit this repository was working unmodified?
